Bugfix/partial fix for ci (#98)
* Ensure activesupport-8 runs with minitest-5 for now

* Change tab to space and use the new logic to permit the clean output

* Change tab to 4

* Clean up scripts to output slightly better info

* Final tidy ups of scripts and addition of TODO to investigate further

* Consistent rubocop value

* Remove redundancies in rubocop

diff --git a/test-gemfile b/test-gemfile
--- a/test-gemfile
+++ b/test-gemfile
@@ -4,29 +4,25 @@ set -e
 
 GEMFILE_FOLDER=$1
 GEMFILE=$GEMFILE_FOLDER/Gemfile
-echo
-echo $GEMFILE
-echo
-scenarios=$(cat $GEMFILE_FOLDER/scenarios)
-
+SCENARIOS=$(cat $GEMFILE_FOLDER/scenarios)
 PLATFORM="$(BUNDLE_GEMFILE=$GEMFILE bundle platform)"
+
+echo
+
 if [[ "$PLATFORM" =~ "Your Ruby version is" ]]; then
-	echo "$PLATFORM"
-	echo
-	echo "Skipping."
-	exit 0
+    echo "$PLATFORM: Skipping"
+    exit 0
 fi
 
-for scenario in $scenarios; do
-	echo
-	echo $scenario
-	echo
-	scenario_path=test/scenarios/$scenario
-	BUNDLE_GEMFILE=$GEMFILE bundle install
-	output=$(BUNDLE_GEMFILE=$GEMFILE bundle exec ruby -I lib test/scenarios/$scenario)
-	if [[ ! -z $output ]]; then
-		echo "Expected output to be empty, but was:"
-		echo "$output"
-		exit 1
-	fi
+for SCENARIO in $SCENARIOS; do
+    SCENARIO_PATH=test/scenarios/$SCENARIO
+    BUNDLE_GEMFILE=$GEMFILE bundle install --quiet
+    OUTPUT=$(BUNDLE_GEMFILE=$GEMFILE bundle exec ruby -I lib "$SCENARIO_PATH")
+    if [[ -n "$OUTPUT" ]] && ! echo "$OUTPUT" | grep -q "0 runs, 0 assertions, 0 failures, 0 errors"; then
+        echo "$GEMFILE_FOLDER -> Scenario: $SCENARIO - FAIL"
+        echo "Expected output to be empty, but was:"
+        echo "$OUTPUT"
+        exit 1
+    fi
+    echo "$GEMFILE_FOLDER -> Scenario: $SCENARIO - PASS"
 done
