Change tab to 4

diff --git a/test-gemfile b/test-gemfile
--- a/test-gemfile
+++ b/test-gemfile
@@ -11,23 +11,23 @@ scenarios=$(cat $GEMFILE_FOLDER/scenarios)
 
 PLATFORM="$(BUNDLE_GEMFILE=$GEMFILE bundle platform)"
 if [[ "$PLATFORM" =~ "Your Ruby version is" ]]; then
-  echo "$PLATFORM"
-  echo
-  echo "Skipping."
-  exit 0
+    echo "$PLATFORM"
+    echo
+    echo "Skipping."
+    exit 0
 fi
 
 for scenario in $scenarios; do
-  echo
-  echo $scenario
-  echo
-  scenario_path=test/scenarios/$scenario
-  BUNDLE_GEMFILE=$GEMFILE bundle install
-  output=$(BUNDLE_GEMFILE=$GEMFILE bundle exec ruby -I lib $scenario_path)
-  if [[ -n "$output" ]] && ! echo "$output" | grep -q "0 runs, 0 assertions, 0 failures, 0 errors"; then
-      echo "Expected output to be empty, but was:"
-      echo "$output"
-      echo "$scenario"
-      exit 1
-  fi
+    echo
+    echo $scenario
+    echo
+    scenario_path=test/scenarios/$scenario
+    BUNDLE_GEMFILE=$GEMFILE bundle install
+    output=$(BUNDLE_GEMFILE=$GEMFILE bundle exec ruby -I lib $scenario_path)
+    if [[ -n "$output" ]] && ! echo "$output" | grep -q "0 runs, 0 assertions, 0 failures, 0 errors"; then
+        echo "Expected output to be empty, but was:"
+        echo "$output"
+        echo "$scenario"
+        exit 1
+    fi
 done
